finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main_app.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("finches/", views.finches_index, name="index"),
    path("finches/<int:finch_id>/", views.finches_detail, name="detail"),
    path("finches/create/", views.FinchCreate.as_view(), name="finches_create"),
    path(
        "finches/<int:pk>/update/", views.FinchUpdate.as_view(), name="finches_update"
    ),
    path(
        "finches/<int:pk>/delete/", views.FinchDelete.as_view(), name="finches_delete"
    ),
    path("finches/<int:finch_id>/add_feeding/", views.add_feeding, name="add_feeding"),
    path(
        "finches/<int:finch_id>/assoc_hat/<int:hat_id>/",
        views.assoc_hat,
        name="assoc_hat",
    ),
    path(
        "finches/<int:finch_id>/unassoc_hat/<int:hat_id>/",
        views.unassoc_hat,
        name="unassoc_hat",
    ),
    path("hats/create/", views.HatCreate.as_view(), name="hats_create"),
    path("hats/", views.hats_index, name="hats_index"),
    path("accounts/signup/", views.signup, name="signup"),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

MEALS = (("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner"))


# Create your models here.
class Hat(models.Model):
    color = models.CharField(max_length=20)
    fabric = models.CharField(max_length=50)


def __str__(self):
    return self.name


def get_absolute_url(self):
    return reverse("hats_detail", kwargs={"pk": self.id})


class Finch(models.Model):
    name = models.CharField(max_length=100)
    species = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    age = models.IntegerField()
    hats = models.ManyToManyField(Hat)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} ({self.id})"

    def get_absolute_url(self):
        return reverse("detail", kwargs={"finch_id": self.id})


class Feeding(models.Model):
    date = models.DateField()
    meal = models.CharField(max_length=1, choices=MEALS, default=MEALS[0])

    # Create a finch_id FK
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

    class Meta:
        ordering = ["-date"]

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ["date", "meal"]

main_app/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch, Hat
from .forms import FeedingForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")


@login_required
def finches_index(request):
    finches = Finch.objects.filter(user=request.user)
    return render(request, "finches/index.html", {"finches": finches})


@login_required
def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    id_list = finch.hats.all().values_list("id")
    hats_finch_doesnt_have = Hat.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    return render(
        request,
        "finches/detail.html",
        {"finch": finch, "feeding_form": feeding_form, "hats": hats_finch_doesnt_have},
    )


@login_required
def add_feeding(request, finch_id):
    # create a ModelForm instance using the data in request.POST
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        new_feeding = form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect("detail", finch_id=finch_id)


class FinchCreate(LoginRequiredMixin, CreateView):
    model = Finch
    fields = ["name", "species", "description", "age"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class FinchUpdate(LoginRequiredMixin, UpdateView):
    model = Finch
    fields = "__all__"


class FinchDelete(LoginRequiredMixin, DeleteView):
    model = Finch
    success_url = "/finches"


@login_required
def hats_index(request):
    hats = Hat.objects.all()
    return render(request, "hats/index.html", {"hats": hats})


class HatCreate(LoginRequiredMixin, CreateView):
    model = Hat
    fields = ["color", "fabric"]
    success_url = "/hats"


@login_required
def assoc_hat(request, finch_id, hat_id):
    Finch.objects.get(id=finch_id).hats.add(hat_id)
    return redirect("detail", finch_id=finch_id)


@login_required
def unassoc_hat(request, finch_id, hat_id):
    Finch.objects.get(id=finch_id).hats.remove(hat_id)
    return redirect("detail", finch_id=finch_id)


def signup(request):
    error_message = ""
    if request.method == "POST":
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect("index")
        else:
            error_message = "Invalid sign up - try again"
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {"form": form, "error_message": error_message}
    return render(request, "registration/signup.html", context)

main_app/templates/about.html
{% extends "base.html" %} {% block content %}
<h1>About Finch Collector</h1>
<p>Finch Collector is an application where avid finch parents can share their finches!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Finch Collector</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <header class="navbar-fixed">
      <div class="header-container">
        <div>
          <a href="{% url 'home' %}" class="left brand-logo">Finch Collector</a>
        </div>
        <ul class="right">
          <!-- changes below -->
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All Cats</a></li>
          <li><a href="{% url 'hats_create' %}">Create a hat</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
  </body>
</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Finch Details</h1>

<div>
  <div>
    <span>{{ finch.name }}</span>
    <p>Species: {{ finch.species }}</p>
    <p>Description: {{ finch.description|linebreaks }}</p>
    <p>Age: {{ finch.age }}</p>
    <div>
      <a href="{% url 'finches_update' finch.id%}">Edit</a>
      <a href="{% url 'finches_delete' finch.id%}">Delete</a>
    </div>
    <br />

    <h3>{{ finch.name }}'s Hats</h3>
    {% if finch.hats %} {% for hat in finch.hats.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> A <span>{{ hat.color }}</span> {{ hat.fabric }} hat </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_hat' finch.id hat.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Hats</h5>
    {% endif %}
    <div class="col s6">
      <h3>Available Hats</h3>
      {% if hats %} {% for hat in hats.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title"> A <span>{{ hat.color }}</span> {{ hat.fabric }} hat</span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_hat' finch.id hat.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
      {% endfor %} {% else %}
      <h5>{{finch.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_feeding' finch.id %}" method="POST">
    {% csrf_token %}
    <!-- Render the inputs -->
    {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding" />
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Meal</th>
      </tr>
    </thead>
    <tbody>
      {% for feeding in finch.feeding_set.all %}
      <tr>
        <td>{{feeding.date}}</td>
        <td>{{feeding.get_meal_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %} {% block content %}

<h1>Finch List</h1>

{% for finch in finches %}
<a href="{% url 'detail' finch.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Species: {{ finch.species }}</p>
      <p>Description: {{ finch.description | linebreaks }}</p>
      <p>Age: {{ finch.age }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/hats/index.html
{% extends 'base.html' %} {% block content %}

<h1>Hat List</h1>

{% for hat in hats %}
  <div class="card">
    <div class="card-content">
      <span class="card-title"> Color: {{ hat.color }}</span>
      <p>Fabric: {{ hat.fabric }}</p>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends "base.html" %} {% block content %}
<h1>HomePage</h1>
{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Finch</h1>

<h4>Are you sure you want to delete <span>{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' finch.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends "base.html" %} {% block content %} {% if object %}
<h1>Edit <span>{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" class="btn" />
</form>

{% endblock %}

main_app/templates/main_app/hat_form.html
{% extends "base.html" %} {% block content %} {% if object %}
<h1>Edit <span>{{object.name}}</span></h1>
{% else %}
<h1>Create Hat</h1>
{% endif %}

<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit" class="btn" />
</form>
 {% endblock %}